//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVoting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineVotingSystemDBEntities : DbContext
    {
        public OnlineVotingSystemDBEntities()
            : base("name=OnlineVotingSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_candidate> tbl_candidate { get; set; }
        public virtual DbSet<tbl_events> tbl_events { get; set; }
        public virtual DbSet<tbl_gender> tbl_gender { get; set; }
        public virtual DbSet<tbl_vote> tbl_vote { get; set; }
        public virtual DbSet<tbl_voter> tbl_voter { get; set; }
    }
}
